const NSFW_KEYWORDS_DEFAULT = Object.freeze([

  /(?<!\p{L})porn(?!\p{L})/iu,
  /(?<!\p{L})pornograph(y|ic|er)/iu,
  /(?<!\p{L})pornstar(?!\p{L})/iu,
  /(?<!\p{L})p[o0]rn(?!\p{L})/iu,
  /(?<!\p{L})pr[o0]n(?!\p{L})/iu,
  /(?<!\p{L})p\*rn(?!\p{L})/iu,
  /(?<!\p{L})p\.o\.r\.n(?!\p{L})/iu,
  /(?<!\p{L})\$ex(?!\p{L})/iu,
  /(?<!\p{L})s\.e\.x(?!\p{L})/iu,
  /(?<!\p{L})0nlyfans(?!\p{L})/iu,
  /(?<!\p{L})pornô(?!\p{L})/iu,
  /(?<!\p{L})porno(?!\p{L})/iu,
  /(?<!\p{L})pornografí(a)(?!\p{L})/iu,
  /(?<!\p{L})pornographie(?!\p{L})/iu,

  /(?<!\p{L})onlyfans(?!\p{L})/iu,
  /(?<!\p{L})fansly(?!\p{L})/iu,
  /(?<!\p{L})chaturbate(?!\p{L})/iu,
  /(?<!\p{L})xvideos(?!\p{L})/iu,
  /(?<!\p{L})xhamster(?!\p{L})/iu,
  /(?<!\p{L})redtube(?!\p{L})/iu,
  /(?<!\p{L})youporn(?!\p{L})/iu,
  /(?<!\p{L})pornhub(?!\p{L})/iu,
  /(?<!\p{L})xnxx(?!\p{L})/iu,
  /(?<!\p{L})brazzers(?!\p{L})/iu,
  /(?<!\p{L})bangbros(?!\p{L})/iu,
  /(?<!\p{L})realitykings(?!\p{L})/iu,
  /(?<!\p{L})naughtyamerica(?!\p{L})/iu,
  /(?<!\p{L})sexfriend(?!\p{L})/iu,
  /(?<!\p{L})sex\s*friend(?!\p{L})/iu,
  /(?<!\p{L})sexcam(?!\p{L})/iu,
  /(?<!\p{L})onlyfans\s*latina(?!\p{L})/iu,

  /(?<!\p{L})xxx(?!\p{L})/iu,

  /(?<!\p{L})18\+(?!\p{L})(?=.*(nude|naked|porn|onlyfans|cam\s*(girl|boy)|adult\s*(film|video)\b))/iu,
  /(?<!\p{L})adults only(?!\p{L})(?=.*(nude|naked|porn|onlyfans|cam\s*(girl|boy)|lewd|hentai))/iu,
  /(?<!\p{L})18 only(?!\p{L})(?=.*(nude|naked|porn|onlyfans|cam\s*(girl|boy)|escort\s*(latina|sexy|vip)))/iu,
  /(?<!\p{L})age[- ]?restricted(?!\p{L})(?=.*(nude|naked|porn|onlyfans|explicit\s*(video|film)|adult\s*(video|film)\b))/iu,

  /(?<!\p{L})adult content(?!\p{L})(?=.*(nude|naked|porn|onlyfans|cam\s*(girl|boy)|lewd|hentai|bdsm|fetish))/iu,
  /(?<!\p{L})conteúdo\s*(adulto|explícito|18\+|sexual)(?!\p{L})(?=.*(nude|naked|porn|pelad|desnud|onlyfans))/iu,
  /(?<!\p{L})contenido\s*(adulto|sexual|explícito)(?!\p{L})(?=.*(nude|porn|desnud|onlyfans|cam\s*(girl|boy)))/iu,
  /(?<!\p{L})contenu\s*(adulte|pour adultes|explicite|sexuel)(?!\p{L})(?=.*(nude|porn|cam\s*(girl|boy)|onlyfans))/iu,

  /(?<!\p{L})nsfw(?!\p{L})(?![_\.\-])(?=.*(nude|naked|porn|onlyfans|lewd|hentai|bdsm|fetish|cam\s*(girl|boy)|escort\s*(sexy|vip)|stripper))/iu,

  /(?<!\p{L})uncensored(?!\p{L})(?=.*(nude|naked|porn|sex\s*tape|cam\s*(girl|boy)|onlyfans|lewd|hentai|bdsm))/iu,

  /(?<!\p{L})explicit(?!\p{L})(?=.*(nude|naked|porn|sex\s*video|sex\s*tape|adult\s*(film|video)|lewd|hentai|onlyfans|bdsm|cam\s*(girl|boy)|fetish|erotic\s*(video|photo|film)|escort\s*(sexy|vip)|stripper))/iu,

  /(?<!\p{L})vidéo\s*x(?!\p{L})/iu,
  /(?<!\p{L})film\s*x(?!\p{L})/iu,
  /(?<!\p{L})site\s*x(?!\p{L})/iu,

  /(?<!\p{L})nud(ity|ist|ism)(?!\p{L})(?!.*art\s*class)(?!.*art\s*history)(?!.*museum)(?!.*fig\s*drawing)(?!.*sculpture\s*class)(?!.*beach\s*resort)(?!.*colony\s*resort)/iu,
  /(?<!\p{L})nude(s)?(?!\p{L})(?!.*art\s*class)(?!.*model\s*for\s*art)(?!.*figure\s*study)(?!.*painting\s*class)(?!.*sculpture\s*studio)/iu,
  /(?<!\p{L})naked(?!\p{L})(?!.*eye)(?!.*truth)(?!.*mole\s*rat)(?!.*singularity)(?!.*fact)(?!.*lunch)(?!.*city\s*of)(?!.*chef\b)/iu,
  /(?<!\p{L})topless(?!\p{L})(?!.*tower)(?!.*bar\s*graph)(?!.*chart)/iu,
  /(?<!\p{L})bottomless(?!\p{L})(?!.*pit)(?!.*brunch)(?!.*cup)(?!.*glass)(?!.*bowl)(?!.*bag)(?!.*coffee)(?!.*refill)/iu,
  /(?<!\p{L})bare(ly)?naked(?!\p{L})/iu,
  /(?<!\p{L})pelad(a|o)(?!\p{L})(?!.*futebol)(?!.*bola)(?!.*jogo)(?!.*campo)(?!.*pelada\s*de)/iu,
  /(?<!\p{L})desnud(o|a|ez)(?!\p{L})(?!.*artístico)(?!.*arte\s)(?!.*pintura)(?!.*escultura)(?!.*fotografia\s*artística)/iu,
  /(?<!\p{L})dénudé(e)?(?!\p{L})/iu,
  /(?<!\p{L})nu(e|dité|disme|diste)?(?!\p{L})(?!.*artistique)(?!.*à nu\b)(?!.*mise à)(?!.*art\b)(?!.*musée)(?!.*peinture)/iu,
  /(?<!\p{L})seins\s*nus(?!\p{L})/iu,
  /(?<!\p{L})encuerad(o|a)(?!\p{L})/iu,
  /(?<!\p{L})sin\s*ropa(?!\p{L})(?!.*deportiva)(?!.*interior)(?!.*de trabajo)/iu,
  /(?<!\p{L})desnuda\s*completamente(?!\p{L})/iu,

  /(?<!\p{L})s[e3]x(?!\p{L})(?!.*education)(?!.*health)(?!.*offend)(?!.*assault)(?!.*abuse)(?!.*therapy)(?!.*ed\b)(?!.*chromosome)(?!.*drive)(?!.*ratio)(?!.*determination)/iu,

  /(?<!\p{L})sexy(?!\p{L})(?=.*(nude|naked|porn|nsfw|onlyfans|explicit\s*(video|photo|film)|lewd|erotic\s*(video|film)|cam\s*(girl|boy)|bdsm|stripper|escort\s*(vip|sexy|latina)))/iu,

  /(?<!\p{L})sexual(?!\p{L})(?!.*education)(?!.*health)(?!.*assault)(?!.*abuse)(?!.*harassment)(?!.*therapy)(?!.*orientation)(?!.*identity)(?!.*reproduction)(?!.*biology)(?!.*dimorphism)(?!.*selection)/iu,

  /(?<!\p{L})sexo(?!\p{L})(?!.*biológico)(?!.*feminino)(?!.*masculino)(?!.*oposto)(?!.*mesmo)(?!.*educação)(?!.*saúde)(?!.*educación)(?!.*salud)(?!.*débil)(?!.*fuerte)/iu,
  /(?<!\p{L})sexe(?!\p{L})(?!.*féminin)(?!.*masculin)(?!.*opposé)(?!.*biologie)(?!.*anatomie)(?!.*genre)(?!.*faible)(?!.*fort)/iu,
  /(?<!\p{L})sexting(?!\p{L})/iu,
  /(?<!\p{L})transar(?!\p{L})(?!.*negócios)(?!.*acordo)(?!.*trânsito)/iu,
  /(?<!\p{L})coito(?!\p{L})/iu,
  /(?<!\p{L})follar(?!\p{L})/iu,
  /(?<!\p{L})fod(e|er|endo|ido|ida)(?!\p{L})/iu,
  /(?<!\p{L})foda(?!\p{L})(?!.*que foda\b)(?!.*essa foda\b)/iu,
  /(?<!\p{L})niquer(?!\p{L})/iu,
  /(?<!\p{L})enculer(?!\p{L})/iu,
  /(?<!\p{L})cogida(?!\p{L})/iu,
  /(?<!\p{L})culear(?!\p{L})/iu,
  /(?<!\p{L})trepad(a|o)(?!\p{L})(?!.*árvore)(?!.*escada)(?!.*muro)(?!.*parede)(?!.*montanha)(?!.*morro)/iu,
  /(?<!\p{L})suruba(?!\p{L})/iu,
  /(?<!\p{L})orgí(a|as)(?!\p{L})/iu,
  /(?<!\p{L})orgie(?!\p{L})/iu,
  /(?<!\p{L})partouze(?!\p{L})/iu,
  /(?<!\p{L})swingers?(?!\p{L})(?!.*music)(?!.*dance)(?!.*jazz)(?!.*big\s*band)(?!.*club\s*dance)/iu,
  /(?<!\p{L})échangisme(?!\p{L})/iu,
  /(?<!\p{L})libertinage(?!\p{L})/iu,
  /(?<!\p{L})libertin(e)?(?!\p{L})(?!.*philosophy)(?!.*enlightenment)(?!.*thought)(?!.*age)/iu,

  /(?<!\p{L})erot(ic|ica|ism)(?!\p{L})(?=.*(nude|naked|porn|video|film|photo|cam\s*(girl|boy)|onlyfans|lewd|bdsm))/iu,

  /(?<!\p{L})lewd(?!\p{L})/iu,
  /(?<!\p{L})lascivious(?!\p{L})/iu,
  /(?<!\p{L})salacious(?!\p{L})/iu,
  /(?<!\p{L})naughty(?!\p{L})(?!.*dog)(?!.*puppy)(?!.*kid)(?!.*child)(?!.*list)(?!.*elf)(?!.*america)(?!.*or\s*nice)(?!.*santa)/iu,
  /(?<!\p{L})slutty(?!\p{L})(?!.*costume\s*guide)(?!.*halloween\s*costume)(?!.*fashion\s*guide)/iu,
  /(?<!\p{L})horny(?!\p{L})(?!.*toad)(?!.*owl)(?!.*lizard)(?!.*bird)(?!.*animal)(?!.*cattle)(?!.*goat)(?!.*rhinoceros)/iu,
  /(?<!\p{L})busty(?!\p{L})/iu,
  /(?<!\p{L})voluptuous(?!\p{L})(?!.*renaissance)(?!.*baroque)(?!.*figure\s*in\s*art)/iu,
  /(?<!\p{L})morboso(?!\p{L})(?!.*curiosidad)(?!.*curioso)/iu,
  /(?<!\p{L})cachond(o|a)(?!\p{L})(?!.*calor)(?!.*temperatura)/iu,
  /(?<!\p{L})tesan(?!\p{L})(?!.*carro)(?!.*música)(?!.*trabalho)(?!.*projeto)(?!.*livro)(?!.*motor)/iu,
  /(?<!\p{L})tarad(o|a)(?!\p{L})(?!.*futebol)(?!.*tecnologia)(?!.*jogo)(?!.*game)(?!.*carro)(?!.*série)/iu,
  /(?<!\p{L})caliente(?!\p{L})(?=\s*(que|muy|bien|rica|rico|mamá|chica|chico|mujer|hombre|noche))/iu,
  /(?<!\p{L})gostosa(?!\p{L})(?=\s*(demais|muito|que|pra caralho|hein|né|assim))/iu,
  /(?<!\p{L})salope(?!\p{L})/iu,
  /(?<!\p{L})cochon(ne)?(?!\p{L})(?!.*d'Inde)(?!.*Inde\b)(?!.*ferme)(?!.*élevage)(?!.*animal)/iu,
  /(?<!\p{L})plan\s*cul(?!\p{L})/iu,
  /(?<!\p{L})exhibitionist(?!\p{L})(?!.*disorder)(?!.*psychology)(?!.*therapy\s*for)/iu,
  /(?<!\p{L})voyeur(ism|iste)?(?!\p{L})(?!.*photography\s*art)(?!.*cinema\s*technique)(?!.*academic)/iu,
  /(?<!\p{L})wank(?!\p{L})(?!.*wankel)(?!.*bank)(?!.*wankle)/iu,

  /(?<!\p{L})masturbat(e|ion|ing|ed)(?!\p{L})/iu,
  /(?<!\p{L})punhet(a|eiro|ando)(?!\p{L})/iu,
  /(?<!\p{L})paj(ear|eo|ero)(?!\p{L})(?!.*mitsubishi)(?!.*carro)(?!.*auto)(?!.*4x4)(?!.*pajero\b)/iu,
  /(?<!\p{L})branl(er|ette|eur)(?!\p{L})/iu,
  /(?<!\p{L})orgasm(?!\p{L})(?!.*disorder)(?!.*dysfunction)(?!.*therapy)/iu,
  /(?<!\p{L})gozad(a|o)(?!\p{L})/iu,
  /(?<!\p{L})éjaculat(ion|er)(?!\p{L})/iu,
  /(?<!\p{L})blowjob(?!\p{L})/iu,
  /(?<!\p{L})boquete(?!\p{L})/iu,
  /(?<!\p{L})mamada(?!\p{L})(?!.*mentira)(?!.*cuento)(?!.*eso es una)(?!.*qué)/iu,
  /(?<!\p{L})chupar\s*pau(?!\p{L})/iu,
  /(?<!\p{L})sucer\s*(la\s*)?(bite|pénis|queue)(?!\p{L})/iu,
  /(?<!\p{L})sodomie(?!\p{L})/iu,
  /(?<!\p{L})sodomiser(?!\p{L})/iu,
  /(?<!\p{L})levrette(?!\p{L})/iu,
  /(?<!\p{L})handjob(?!\p{L})/iu,
  /(?<!\p{L})footjob(?!\p{L})/iu,
  /(?<!\p{L})rimjob(?!\p{L})/iu,
  /(?<!\p{L})cumshot(?!\p{L})/iu,
  /(?<!\p{L})creampie(?!\p{L})(?!.*recipe)(?!.*dessert)(?!.*pastry)(?!.*bakery)/iu,
  /(?<!\p{L})gangbang(?!\p{L})/iu,
  /(?<!\p{L})threesome(?!\p{L})/iu,
  /(?<!\p{L})threeway(?!\p{L})/iu,
  /(?<!\p{L})foursome(?!\p{L})(?!.*golf)(?!.*music\s*group)/iu,
  /(?<!\p{L})facial(?!\p{L})(?!.*hair)(?!.*cream)(?!.*cleanser)(?!.*wash)(?!.*mask)(?!.*treatment)(?!.*recognition)(?!.*surgery)(?!.*feature)(?!.*analysis)(?!.*expression)/iu,
  /(?<!\p{L})squirt(?!\p{L})(?!.*bottle)(?!.*gun)(?!.*water)(?!.*juice)(?!.*plant)(?!.*flower)(?!.*brand)(?!.*drink)(?!.*soda)/iu,
  /(?<!\p{L})dick\s*pic(s)?(?!\p{L})/iu,
  /(?<!\p{L})chingar(?!\p{L})(?=\s*(bien|mal|fuerte|duro|todo|se\s))/iu,
  /(?<!\p{L})gozar\s*gostoso(?!\p{L})/iu,
  /(?<!\p{L})pauzudo(?!\p{L})/iu,
  /(?<!\p{L})bucetuda(?!\p{L})/iu,
  /(?<!\p{L})pegging(?!\p{L})/iu,
  /(?<!\p{L})glory\s*hole(?!\p{L})/iu,
  /(?<!\p{L})findom(?!\p{L})/iu,
  /(?<!\p{L})femdom(?!\p{L})/iu,
  /(?<!\p{L})maledom(?!\p{L})/iu,

  /(?<!\p{L})buceta(?!\p{L})/iu,
  /(?<!\p{L})boceta(?!\p{L})/iu,
  /(?<!\p{L})xota(?!\p{L})/iu,
  /(?<!\p{L})xoxota(?!\p{L})/iu,
  /(?<!\p{L})xereca(?!\p{L})/iu,
  /(?<!\p{L})coño(?!\p{L})/iu,
  /(?<!\p{L})chatte(?!\p{L})(?!.*chaton)(?!.*petite\s*chatte)(?!.*ma\s*chatte\s*\w)/iu,
  /(?<!\p{L})piroca(?!\p{L})/iu,
  /(?<!\p{L})pinto(?!\p{L})(?!.*bird)(?!.*feather)(?!.*Pinto\s[A-Z])(?!.*feijão)(?!.*cor)(?!.*tinta)/iu,
  /(?<!\p{L})pau(?!\p{L})(?=\s*(duro|grande|gostoso|grosso|dentro|fora|na boca|no cu|comprido))/iu,
  /(?<!\p{L})verga(?!\p{L})(?!.*de\s*(toro|maçã|madeira|aço|ferro))/iu,
  /(?<!\p{L})polla(?!\p{L})/iu,
  /(?<!\p{L})pene(?!\p{L})(?!.*penetración\s*de mercado)(?!.*muscular)/iu,
  /(?<!\p{L})bite(?!\p{L})(?=\s*(grosse|dure|dans|au|le\s+cul|de\s+chien))/iu,
  /(?<!\p{L})bund(a|ão|inha)(?!\p{L})(?!.*mole\b)(?!.*covarde)/iu,
  /(?<!\p{L})cu(?!\p{L})(?=\s*(gozado|peludo|grande|apertado|fedorento|molhado))/iu,
  /(?<!\p{L})culo(?!\p{L})(?!.*músculo)(?!.*Hércules)/iu,
  /(?<!\p{L})culona(?!\p{L})/iu,
  /(?<!\p{L})nalgona(?!\p{L})/iu,
  /(?<!\p{L})tetas?(?!\p{L})(?!.*bebé)(?!.*baby)(?!.*leche)(?!.*lactancia)/iu,
  /(?<!\p{L})tetona(?!\p{L})/iu,
  /(?<!\p{L})téton(s)?(?!\p{L})/iu,
  /(?<!\p{L})pezones?(?!\p{L})/iu,
  /(?<!\p{L})zorr(a|o)(?!\p{L})(?!.*animal)(?!.*zorro\s*(the|show|serie|fox))/iu,
  /(?<!\p{L})clito(?!\p{L})/iu,

  /(?<!\p{L})fetish(?!\p{L})(?!.*cultural\s*anthropology)(?!.*anthropological\s*study)/iu,
  /(?<!\p{L})bdsm(?!\p{L})/iu,
  /(?<!\p{L})bondage(?!\p{L})(?!.*paper)(?!.*tape\s*art)(?!.*debt)(?!.*financial)(?!.*economic)/iu,
  /(?<!\p{L})dominatrix(?!\p{L})/iu,
  /(?<!\p{L})dominatrice(?!\p{L})/iu,
  /(?<!\p{L})sadomasoch(ism|ist)(?!\p{L})/iu,
  /(?<!\p{L})sado[- ]?maso(?!\p{L})/iu,
  /(?<!\p{L})kink(y)?(?!\p{L})(?!.*hair)(?!.*curl)(?!.*twist)(?!.*hose)(?!.*kinky\s*boots)(?!.*musical)(?!.*broadway)/iu,
  /(?<!\p{L})softcore(?!\p{L})/iu,
  /(?<!\p{L})hardcore(?!\p{L})(?!.*game)(?!.*gaming)(?!.*gamer)(?!.*music)(?!.*punk)(?!.*fan)(?!.*workout)(?!.*training)(?!.*hiker)(?!.*parkour)(?!.*sport)(?!.*athlete)(?!.*collector)(?!.*enthusiast)/iu,
  /(?<!\p{L})fessée(?!\p{L})(?!.*enfant)(?!.*bébé)(?!.*punition\s*parent)/iu,
  /(?<!\p{L})sm\b(?=\s*(session|pratique|fetish|master|slave|play))/iu,
  /(?<!\p{L})cuckolding(?!\p{L})/iu,
  /(?<!\p{L})cuckold(?!\p{L})/iu,

  /(?<!\p{L})dildo(?!\p{L})/iu,
  /(?<!\p{L})vibrator(?!\p{L})(?!.*back massager)(?!.*phone)(?!.*engine)(?!.*motor)(?!.*industrial)/iu,
  /(?<!\p{L})fleshlight(?!\p{L})/iu,
  /(?<!\p{L})butt\s*plug(?!\p{L})/iu,
  /(?<!\p{L})sex\s*toy(s)?(?!\p{L})/iu,
  /(?<!\p{L})consolador(?!\p{L})(?!.*palabras)(?!.*mensaje)(?!.*voz)(?!.*pensamiento)/iu,

  /(?<!\p{L})stripper(?!\p{L})(?!.*paint)(?!.*wallpaper)(?!.*wire)(?!.*cable)(?!.*log)(?!.*tool)(?!.*insulation)(?!.*electrical)(?!.*bark)/iu,
  /(?<!\p{L})striptease(?!\p{L})/iu,
  /(?<!\p{L})escort(?!\p{L})(?!.*vehicle)(?!.*military)(?!.*service\s*car)(?!.*fighter)(?!.*jet)(?!.*police)(?!.*carrier)(?!.*fleet)/iu,
  /(?<!\p{L})escorte(?!\p{L})(?!.*policière)(?!.*militaire)(?!.*armée)(?!.*garde)(?!.*sous)/iu,
  /(?<!\p{L})prostitut(e|ion|ed)(?!\p{L})/iu,
  /(?<!\p{L})prostituée(?!\p{L})/iu,
  /(?<!\p{L})prostituta(?!\p{L})/iu,
  /(?<!\p{L})camgirl(?!\p{L})/iu,
  /(?<!\p{L})camboy(?!\p{L})/iu,
  /(?<!\p{L})sugar daddy(?!\p{L})/iu,
  /(?<!\p{L})sugar momm(y|a)(?!\p{L})/iu,
  /(?<!\p{L})sex work(er)?(?!\p{L})(?!.*law)(?!.*policy)(?!.*decriminal)(?!.*rights)(?!.*reform)(?!.*research)/iu,
  /(?<!\p{L})onlyfans?\s*model(?!\p{L})/iu,
  /(?<!\p{L})michê(?!\p{L})/iu,
  /(?<!\p{L})puteiro(?!\p{L})/iu,
  /(?<!\p{L})garota\s*de\s*programa(?!\p{L})/iu,
  /(?<!\p{L})acompanhante(?!\p{L})(?=\s*(sexy|sensual|adulto|adulta|vip|exclusiv|erótic))/iu,
  /(?<!\p{L})puta\s*callejera(?!\p{L})/iu,
  /(?<!\p{L})escort\s*(latina|sexy|vip|exclusiva|gfe)/iu,
  /(?<!\p{L})chica(s)?\s*(escort|vip|prepago|sexy)(?!\p{L})/iu,
  /(?<!\p{L})putari(a)(?!\p{L})/iu,
  /(?<!\p{L})putería(?!\p{L})/iu,
  /(?<!\p{L})pute(?!\p{L})(?!.*dispute)(?!.*répute)(?!.*impute)/iu,
  /(?<!\p{L})puta(?!\p{L})(?!.*merda)(?!.*vida)(?!.*que pariu)(?!.*sorte)(?!.*madre)(?!.*suerte)(?!.*mierda)(?!.*putativo)/iu,
  /(?<!\p{L})vadi(a|o)(?!\p{L})/iu,
  /(?<!\p{L})vagabund(a|o)(?!\p{L})(?!.*vida)(?!.*esse\s)(?!.*que\s)(?!.*é\s*um)/iu,
  /(?<!\p{L})safad(a|o|agem)(?!\p{L})(?!.*roubou)(?!.*ladrão)(?!.*esse\s*safado\s*me)/iu,
  /(?<!\p{L})corno(?!\p{L})(?!.*corno\s*de\s*caça)(?!.*unicórnio)/iu,
  /(?<!\p{L})massage\s*(érotique|sensuel(le)?)(?!\p{L})/iu,

  /(?<!\p{L})milf(?!\p{L})/iu,
  /(?<!\p{L})gilf(?!\p{L})/iu,
  /(?<!\p{L})dilf(?!\p{L})/iu,
  /(?<!\p{L})tilf(?!\p{L})/iu,
  /(?<!\p{L})wilf(?!\p{L})/iu,
  /(?<!\p{L})cougar(?!\p{L})(?!.*animal)(?!.*cat)(?!.*mountain\s*lion)(?!.*car)(?!.*team)(?!.*puma)(?!.*helicopter)(?!.*aircraft)/iu,
  /(?<!\p{L})novinha(?!\p{L})/iu,
  /(?<!\p{L})novinhas(?!\p{L})/iu,

  /(?<!\p{L})nudes?\s*(leak|send|share|swap|request|gratis)/iu,
  /(?<!\p{L})nudes?\s*(vazar|vazou|caiu|grátis|venda|vendo|caindo)/iu,
  /(?<!\p{L})pack\s*(nudes?|fotos|vídeos|videos|hot)(?!\p{L})/iu,
  /(?<!\p{L})snap(chat)?\s*(nudes?|naked|explicit)/iu,
  /(?<!\p{L})privacy\s*girl(?!\p{L})/iu,
  /(?<!\p{L})feet\s*pics?(?!\p{L})/iu,
  /(?<!\p{L})vizinha\s*(safada|gostosa|pelada|nua)(?!\p{L})/iu,
  /(?<!\p{L})breeding\s*(fetish|kink|porn)(?!\p{L})/iu,

  /(?<!\p{L})hentai(?!\p{L})/iu,
  /(?<!\p{L})ecchi(\s*na)?(?!\p{L})/iu,
  /(?<!\p{L})eroge(?!\p{L})/iu,
  /(?<!\p{L})nukige(?!\p{L})/iu,
  /(?<!\p{L})ero\s*(manga|anime|game|doujin)(?!\p{L})/iu,
  /(?<!\p{L})ahegao(?!\p{L})/iu,
  /(?<!\p{L})doujin(shi)?(?!\p{L})(?=.*(porn|hentai|nsfw|nude|naked|lewd|explicit|erotic|adult|18\+))/iu,
  /(?<!\p{L})futanari(?!\p{L})/iu,
  /(?<!\p{L})oppai(?!\p{L})(?=.*(hentai|nude|naked|lewd|nsfw|explicit|ecchi))/iu,
  /(?<!\p{L})oshiri(?!\p{L})(?=.*(hentai|nude|naked|lewd|nsfw|explicit|ecchi))/iu,
  /(?<!\p{L})sukebe(?!\p{L})/iu,
  /(?<!\p{L})pantsu(?!\p{L})(?!.*fashion)(?!.*clothing)(?!.*brand)(?!.*store)/iu,
  /(?<!\p{L})tentacle\s*(porn|hentai|sex)(?!\p{L})/iu,
  /(?<!\p{L})netorare(?!\p{L})/iu,
  /(?<!\p{L})ntr\b(?=\s*(hentai|doujin|manga|anime|porn))/iu,
  /(?<!\p{L})yariman(?!\p{L})/iu,
  /(?<!\p{L})chikan(?!\p{L})/iu,
  /(?<!\p{L})enjo\s*kosai(?!\p{L})/iu,
  /(?<!\p{L})soapland(?!\p{L})/iu,
  /(?<!\p{L})fuzoku(?!\p{L})/iu,
  /(?<!\p{L})av\s*(actress|actor|idol|star|video)(?!\p{L})/iu,
  /(?<!\p{L})joshi\s*kosei(?!\p{L})(?=.*nude|.*naked|.*porn|.*hentai|.*explicit|.*nsfw)/iu,
  /(?<!\p{L})imouto(?!\p{L})(?=.*nude|.*naked|.*porn|.*hentai|.*explicit|.*nsfw|.*lewd)/iu,
  /(?<!\p{L})oniichan(?!\p{L})(?=.*nude|.*naked|.*porn|.*hentai|.*explicit|.*nsfw|.*lewd)/iu,
  /(?<!\p{L})rape\s*(hentai|anime|manga|doujin|fantasy)(?!\p{L})/iu,
  /(?<!\p{L})r34(?!\p{L})/iu,
  /(?<!\p{L})rule\s*34(?!\p{L})/iu,

  /(?<!\p{L})lolicon(?!\p{L})/iu,
  /(?<!\p{L})shotacon(?!\p{L})/iu,
  /(?<!\p{L})shota(?!\p{L})/iu,
  /(?<!\p{L})csam(?!\p{L})/iu,
  /(?<!\p{L})cp(?!\p{L})(?=.*porn|.*sex|.*nude|.*naked|.*explicit)/iu,
  /(?<!\p{L})minor(s)?(?!\p{L})(?=.*porn|.*sex|.*nude|.*naked|.*explicit)/iu,
  /(?<!\p{L})underage(?!\p{L})(?=.*porn|.*sex|.*nude|.*explicit)/iu,
  /naked\s*(loli|shota|child|minor|kid)/iu,
  /(?<!\p{L})児童ポルノ(?!\p{L})/iu,

]);